version: '3'
services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql-container
      - DB_PORT=3306
    ports:
      - "9000:9000"
volumes:
  mysql-data:
